services:
  - type: web
    name: spesetta-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_server:app"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
